#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-pyOpenSSL
Version  : 19.0.0
Release  : 71
URL      : https://pypi.debian.net/pyOpenSSL/pyOpenSSL-19.0.0.tar.gz
Source0  : https://pypi.debian.net/pyOpenSSL/pyOpenSSL-19.0.0.tar.gz
Summary  : Python wrapper module around the OpenSSL library
Group    : Development/Tools
License  : Apache-2.0
Requires: deprecated-pyOpenSSL-license = %{version}-%{release}
Requires: deprecated-pyOpenSSL-python = %{version}-%{release}
Requires: cryptography
Requires: six
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : cffi
BuildRequires : cffi-python
BuildRequires : cryptography
BuildRequires : deprecated-cffi-legacypython
BuildRequires : deprecated-cryptography-legacypython
BuildRequires : deprecated-ipaddress-legacypython
BuildRequires : deprecated-pyasn1-legacypython
BuildRequires : deprecated-pycparser-legacypython
BuildRequires : enum34
BuildRequires : enum34-legacypython
BuildRequires : idna-python
BuildRequires : ipaddress-python
BuildRequires : openssl-dev
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pyasn1
BuildRequires : pycparser
BuildRequires : pycparser-python
BuildRequires : pytest
BuildRequires : setuptools-legacypython
BuildRequires : six
BuildRequires : tox
BuildRequires : virtualenv

%description
This directory contains client and server examples for the "Server Name
Indication" (SNI) feature.

%package legacypython
Summary: legacypython components for the deprecated-pyOpenSSL package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-pyOpenSSL package.


%package license
Summary: license components for the deprecated-pyOpenSSL package.
Group: Default

%description license
license components for the deprecated-pyOpenSSL package.


%package python
Summary: python components for the deprecated-pyOpenSSL package.
Group: Default
Provides: deprecated-pyopenssl-python

%description python
python components for the deprecated-pyOpenSSL package.


%prep
%setup -q -n pyOpenSSL-19.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554326313
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-pyOpenSSL
cp LICENSE %{buildroot}/usr/share/package-licenses/deprecated-pyOpenSSL/LICENSE
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-pyOpenSSL/LICENSE

%files python
%defattr(-,root,root,-)
